repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Tests
        entry: python3 -m unittest discover
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
